site_name: My Docs
repo_url: https://github.com/ahforganization/documentation
repo_name: documentation

theme: 
  name: material
  language: en
  palette:
    primary: deep_orange
    accent: amber

plugins:
  - include-markdown
  - search
nav:
  - Home: index.md
  - Ahmed: '!include: ./ahmed/mkdocs.yml'
  - Dalia: '!include: ./dalia/mkdocs.yml'

extra:
  feature:
    tabs: trues